### ISSUE TITLE
Frodo

### ISSUE THREAD

**Issue by miguellopes** [paddycarey/plugin.video.vice#1]
In Frodo it doesn't play video just the sound. I can get the video only with vlc.
And also needs to convert the encoding of the arguments on addVideo.
    url = sys.argv[0] + "?episode_link=%s&episode_name=%s&episode_thumb=%s" % (episode_link, urllib.quote(linkName.encode('utf-8')), urllib.quote(thumbPath.encode('utf-8')))

**Comment by mablae** [comment]
How to install BeatifulSoup dependency? Script crashes on Frodo Startup! 

+1
